# Generated by Django 4.1.7 on 2023-03-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='heroes.ability'),
        ),
    ]
