# Generated by Django 4.1.7 on 2023-03-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_ability_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='ability',
        ),
    ]
