# Generated by Django 4.1.7 on 2023-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_remove_ability_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='abilities',
            field=models.ManyToManyField(to='heroes.ability'),
        ),
    ]
