# Generated by Django 4.1.7 on 2023-03-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_ability_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='abilities',
        ),
    ]
