# Generated by Django 4.1.7 on 2023-03-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_remove_ability_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='abilities',
            field=models.ManyToManyField(to='heroes.hero'),
        ),
    ]
