# Generated by Django 4.1.7 on 2023-03-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_alter_hero_about_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='ability',
            name='abilities',
        ),
        migrations.AddField(
            model_name='hero',
            name='abilities',
            field=models.ManyToManyField(blank=True, null=True, related_name='heroes', to='heroes.ability'),
        ),
    ]
