# Generated by Django 4.1.7 on 2023-03-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0010_alter_ability_options_alter_hero_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='abilities',
        ),
        migrations.AddField(
            model_name='ability',
            name='abilities',
            field=models.ManyToManyField(to='heroes.hero'),
        ),
    ]
