# Generated by Django 4.1.7 on 2023-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0011_remove_hero_abilities_ability_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='abilities',
            field=models.ManyToManyField(to='heroes.ability'),
        ),
    ]
