# Generated by Django 4.1.7 on 2023-03-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0012_hero_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='abilities',
        ),
    ]
